name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker image with tests only
      run: docker build -t aerosol-test . --build-arg BUILD=AERO_TESTS_ONLY
    - name: Build library and run tests in DEBUG
      run: docker run -t aerosol-test bash -c 'cd /build; cmake -D CMAKE_BUILD_TYPE=Debug -D AERO_TESTS_ONLY:BOOL=TRUE ../aerosol/; make; make test'
    - name: Build library and run tests in RELEASE
      run: docker run -t aerosol-test bash -c 'cd /build; cmake -D CMAKE_BUILD_TYPE=Release -D AERO_TESTS_ONLY:BOOL=TRUE ../aerosol/; make; make test'
